### ISSUE TITLE
Domain and redirection

### ISSUE THREAD

**Issue by d-asensio** [TypeStrong/typedoc-site#1]
Hi @blakeembrey I have re-created the site with gh-pages support and Jekyll, the problem is that http://typestrong.github.io/ has a redirection to http://typestrong.org/ and for this reason the typedoc site cannot be shown :(. Any idea to solve this?, note that https://github.com/TypeStrong/typestrong.github.io contains only a _CNAME_ and a _index.html_ file with almost nothing inside?

At the other hand, all is ready to purchase the domain, do you need a contribution to purchase it?

**Comment by blakeembrey** [comment]
It's not going to need `typestrong.github.io`, so let's just avoid it. On the domain side, do you want to create the CNAME file for `typedoc.org`? I'll set up the domain today 😄

**Comment by d-asensio** [comment]
Done! 😄

**Comment by blakeembrey** [comment]
Looks like it's working! Thanks for your help 😄 

See http://typedoc.org/

**Comment by blakeembrey** [comment]
Just a note though, it does look like there's a lot more to do (maybe porting issues?). None of the linked documents work.

**Comment by d-asensio** [comment]
Yes, was a problem with Jekyll and case sensitive, I just fixed it.

In addition, I have not generated the API documentation yet, I will do it between today and monday, I can quit the link from the menu for now.

**Comment by aciccarello** [comment]
Can we regenerate the api docs? http://typedoc.org/api/ is still using a readme that references typedoc.io and the "Generated by TypeDoc" links in the bottom of the api pages also reference typedoc.io

**Comment by aciccarello** [comment]
I've regenerated the api docs with the following options. I hope to automate this at some point.

>  typedoc --out typedoc-site/api --tsconfig tsconfig.json src/lib --name "TypeDoc Documentation" --mode file

**Comment by cloudrex** [comment]
https://typedoc.org/guides/installation/ the "usage" link under the "Task runners" section is broken.

**Comment by aciccarello** [comment]
Thanks for reporting that @cloudrex. It should be fixed now. Next time, would you mind opening a new issue so it can be tracked separately?
