### ISSUE TITLE
Documentation Update?

### ISSUE THREAD

**Issue by johnjacobkenny** [TypeStrong/typedoc-site#2]
Hi guys,

I was looking at how to hide certain functions from appearing in the generated typedocs and I couldn't find any mention of it on the website. Eventually I found a comment in the issues that suggests using `@hidden`. (see https://github.com/TypeStrong/typedoc/issues/62#issuecomment-74159413)

Is the documentation complete and to an extent up to date?

Thanks!

**Comment by aciccarello** [comment]
@kennyjacob Honestly it is not very up to date right now. Any PRs for suggested improvements would be welcome.

**Comment by mootari** [comment]
The Usage guide also misses the option `--excludePrivate`, added in https://github.com/TypeStrong/typedoc/pull/293
